---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: cinder-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: cinder-global
      component: cinder
    actions:
      - method: merge
        path: .
      - method: replace
        path: .values.pod
      - method: delete
        path: .values.ceph_client
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.cinder.api.min
      dest:
        path: .values.pod.replicas.api
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.cinder.volume.min
      dest:
        path: .values.pod.replicas.volume
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.cinder.scheduler.min
      dest:
        path: .values.pod.replicas.scheduler
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.cinder.backup.min
      dest:
        path: .values.pod.replicas.backup
data:
  wait:
    timeout: {{ openstack_helm_deploy_timeout }}
  test:
    enabled: {{ run_tests }}
    timeout: {{ test_timeout }}
  values:
    pod:
      resources:
        enabled: {{ openstack_helm_pod_resources_enabled['cinder'] }}
      replicas:
        api: 1
        volume: 1
        scheduler: 1
        backup: 1
    storage: rbd
    conf:
      software:
        rbd:
          rbd_pool_app_name_backup: rbd
          rbd_pool_app_name: rbd
      ceph:
        enabled: true
        monitors: {{ ','.join(suse_deploy_ceph_mons) }}
        admin_keyring: {{ ceph_admin_keyring_b64key | b64decode }}
        pools:
          {{ ses_cluster_configuration['cinder']['rbd_store_pool'] }}:
            replication: 3
            crush_rule: replicated_rule
            chunk_size: 8
            app_name: cinder-volume
      cinder:
        DEFAULT:
          debug: true
          backup_driver: cinder.backup.drivers.ceph
          backup_ceph_user: {{ ses_cluster_configuration['cinder-backup']['rbd_store_user'] }}
          backup_ceph_pool: {{ ses_cluster_configuration['cinder-backup']['rbd_store_pool'] }}
      backends:
        rbd1:
          volume_driver: cinder.volume.drivers.rbd.RBDDriver
          volume_backend_name: rbd1
          rbd_ceph_conf: "/etc/ceph/ceph.conf"
          rbd_user: {{ ses_cluster_configuration['cinder']['rbd_store_user'] }}
          rbd_pool: {{ ses_cluster_configuration['cinder']['rbd_store_pool'] }}
          rbd_secret_uuid: {{ libvirt_ceph_cinder_secret_uuid }}
...
