---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: cinder-rabbitmq-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: cinder-rabbitmq-global
      component: cinder
    actions:
      - method: delete
        path: .values.labels.prometheus_rabbitmq_exporter
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.rabbitmq.storage_class
      dest:
        path: .values.volume.class_name
data:
  wait:
    timeout: {{ openstack_helm_deploy_timeout }}
  test:
    enabled: {{ run_tests }}
    timeout: {{ test_timeout }}
  values:
    pod:
      resources:
        enabled: {{ openstack_helm_pod_resources_enabled['cinder_rabbitmq'] }}
      replicas:
        server: 1
    monitoring:
      prometheus:
        enabled: false
    volume:
      size: {{ rabbitmq_volume_size }}
...
