---
# defaults file for deploy-osh

base_env_vars:
  OSH_INFRA_PATH: /opt/openstack/openstack-helm-infra

suse_osh_deploy_require_ha: True

# Example SES secrets per pool.
# This should be appearing only in your user variables.
#suse_ses_cinder_pool_key:
#suse_ses_cinder_backup_pool_key:
#suse_ses_glance_pool_key:

# These variables were created to provide a way for deployers to
# override the default registry, for example to point to a local
# registry. This change will apply to all the charts value files by
# default, as all our own value files are including a common file
# (files/common-images-overrides.yml) making use of those variables.
# Check the variables there.
# For the registry case, the local registry should still have the same
# groups as upstream registry (kolla, openstackhelm), and the same image names.
# For versions, use suse_osh_image_version for a global OpenStack version change
# accross all images (as it is defined in common-images-overrides which is
# included in all the places).
# For a more surgical per component approach, use service overrides, like
# suse_osh_deploy_cinder_yaml_overrides for cinder for example.
suse_osh_image_version: "ocata"

# Default overrides
suse_osh_deploy_barbican_yaml_overrides: {}
suse_osh_deploy_cinder_yaml_overrides: {}
suse_osh_deploy_glance_yaml_overrides: {}
suse_osh_deploy_ingress_kube_system_yaml_overrides: {}
suse_osh_deploy_ingress_namespace_yaml_overrides: {}
suse_osh_deploy_keystone_yaml_overrides: {}
suse_osh_deploy_horizon_yaml_overrides: {}
suse_osh_deploy_heat_yaml_overrides: {}
suse_osh_deploy_libvirt_yaml_overrides: {}
suse_osh_deploy_mariadb_yaml_overrides: {}
suse_osh_deploy_memcached_yaml_overrides: {}
suse_osh_deploy_nova_yaml_overrides: {}
suse_osh_deploy_ovs_yaml_overrides: {}
suse_osh_deploy_rabbitmq_yaml_overrides: {}
suse_osh_deploy_neutron_yaml_overrides: {}
suse_osh_deploy_tempest_yaml_overrides: {}

# override in your extravars to deploy and run tempest
deploy_tempest: True
