language: python
cache: pip
dist: xenial

matrix:
  include:
    - name: "shell syntax"
      script: find . -path "./submodules" -prune -o -path "./files" -prune -o -type f -name "*.sh" -print | xargs -n1 shellcheck -x --format=gcc
    - name: "playbook syntax"
      script: ansible-lint playbooks/*.yml
      install: pip install ansible-lint
