---
- hosts: all:!localhost
  tasks:
    - include_vars: ../common-vars.yml

    - name: Copy SES config in userspace
      copy:
        src: "/tmp/ses_config/ses_config.yml"
        dest: "{{ suse_osh_deploy_ses_config_path }}"
        remote_src: yes
      delegate_to: localhost

      ## TODO(evrardjp): Add return code to latest call to make sure idempotency is known.
      ## This step is commented, as we should be trusting the result of ses provisioning.
      # Should we decide to not trust said results, we can uncomment this, and be explicit about the expectations.
      #- name: Create pools
      #  shell: "ceph -k /etc/ceph/ceph.client.admin.keyring osd pool ls | grep {{ item }} || ceph -k /etc/ceph/ceph.client.admin.keyring osd pool create {{ item }} 128 128"
      #  with_items:
      #    - rbd
      #    - volumes
      #    - cinder_backup
      #    - images
      #    - vms
