---
- name: Include common vars
  include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"

- name: Copy the certificates
  become: True
  copy:
    src: "{{ socok8s_registry_cert }}"
    dest: "/etc/pki/trust/anchors"
  register: _copiedcert

- block:
    - name: Refresh ca certs
      become: True
      command: update-ca-certificates

    - name: Populate service info
      service_facts:

    - name: Restart docker
      become: True
      when: "'docker.service' in services"
      service:
        name: docker
        state: restarted

    - name: Restart crio
      become: True
      when: "'crio.service' in services"
      service:
        name: crio
        state: restarted
  when: _copiedcert is changed
