---
deploy_tempest: true
tempest_test_type: "smoke"
tempest_test_args:
  smoke:  "--smoke"
  all: "--regex '.*'"
tempest_workers: 4
tempest_enable_cinder_service: true
tempest_enable_glance_service: true
tempest_enable_nova_service: true
tempest_enable_neutron_service: true
tempest_provider_physical_network: eth0
tempest_network_prefix: "{{ lookup('env', 'SOCOK8S_ENVNAME') }}-tempest"
openstack_external_network_name: "{{ tempest_network_prefix}}-public"
openstack_external_subnet_name: "{{ tempest_network_prefix }}-public-subnet"
# used by tempest, input required for kvm deployment mechanism
openstack_project_network_cidr:
# used by tempest for ssh connection to servers, input used in kvm deployment mechanism
openstack_external_network_cidr: "10.23.24.0/24"
tempest_network_address_start_index: 11
cirros_test_image_url: "http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
use_blacklist: true
# Flag to hide tempest pod logs during ansible tempest run. Default is True (show tempest logs)
print_tempest_log: "{{ lookup('env','AIRSHIP_TEMPEST_LOG_STDOUT') | default('True', true) | bool }}"
# wheter to output tempest in subunit format
tempest_subunit: "{{ lookup('env', 'SOCOK8S_TEMPEST_SUBUNIT_OUTPUT') | default(False, True) | bool }}"
