---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-rabbitmq-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-rabbitmq-global
    actions:
      - method: merge
        path: .
  substitutions:
    - src:
        schema: pegleg/PodScaleProfile/v1
        name: pod-scale-profile
        path: .pods.osh.rabbitmq.server.min
      dest:
        path: .values.pod.replicas.server
  storagePolicy: cleartext
data:
  wait:
    timeout: {{ openstack_helm_deploy_timeout }}
  test:
    enabled: {{ run_tests }}
    timeout: {{ test_timeout }}
  values:
    # disable monitoring stuff as we are not using it currently
    manifests:
      monitoring:
        prometheus:
          configmap_bin: false
          deployment_exporter: false
          service_exporter: false
...
