---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Include standard vars
      include_vars: ../common-vars.yml

    - name: Ensuring ses config is available
      stat:
        path: "{{ ses_config_file_path }}"
      register: _sesconfigfile

    - name: Exit if file doesn't exist
      fail:
        msg: "ses config not found"
      when:
        - not _sesconfigfile.stat.exists | bool

    - name: Loading the ses variables
      include_vars: "{{ ses_config_file_path }}"

    - name: Ensuring data of the ses_config_file_path contains the right information
      debug:
        var: item
      with_items:
        - "{{ ses_cluster_configuration['conf_options']['ses_mon_host'] }}"
        - "{{ ses_cluster_configuration['cinder']['rbd_store_pool'] }}"
        - "{{ ses_cluster_configuration['nova']['rbd_store_pool'] }}"

    - name: Get info of osds pools from the ceph-mon node
      command: ceph -k /etc/ceph/ceph.client.admin.keyring osd pool ls
      changed_when: false
      remote_user: root
      delegate_to: "{{ ceph_monitors_ips[0] }}"
      register: _ceph_pools

    # TODO(evrardjp): Update this list with the content of ses_cluster_configuration when
    # we'll start using the ses_config's ses_cluster_configuration to properly isolate data
    - name: Ensuring the ceph pools have all we need
      assert:
        that:
          - _ceph_pools.stdout.find('rbd') != -1
          - _ceph_pools.stdout.find('volumes') != -1
          - _ceph_pools.stdout.find('cinder_backup') != -1
          - _ceph_pools.stdout.find('images') != -1
          - _ceph_pools.stdout.find('vms') != -1

