images:
  tags:
    congress_api: "{{ suse_osh_registry_location }}/openstackhelm/congress:{{ suse_osh_image_version }}"
    congress_datasource: "{{ suse_osh_registry_location }}/openstackhelm/congress:{{ suse_osh_image_version }}"
    congress_db_sync: "{{ suse_osh_registry_location }}/openstackhelm/congress:{{ suse_osh_image_version }}"
    congress_ds_create: "{{ suse_osh_registry_location }}/openstackhelm/congress:{{ suse_osh_image_version }}"
    congress_policy_engine: "{{ suse_osh_registry_location }}/openstackhelm/congress:{{ suse_osh_image_version }}"
    congress_scripted_test: "{{ suse_osh_registry_location }}/openstackhelm/congress:{{ suse_osh_image_version }}"
    ironic_api: "{{ suse_osh_registry_location }}/openstackhelm/ironic:{{ suse_osh_image_version }}"
    ironic_bootstrap: "{{ suse_osh_registry_location }}/openstackhelm/ironic:{{ suse_osh_image_version }}"
    ironic_conductor: "{{ suse_osh_registry_location }}/openstackhelm/ironic:{{ suse_osh_image_version }}"
    ironic_db_sync: "{{ suse_osh_registry_location }}/openstackhelm/ironic:{{ suse_osh_image_version }}"
    ironic_pxe: "{{ suse_osh_registry_location }}/openstackhelm/ironic:{{ suse_osh_image_version }}"
    ironic_pxe_init: "{{ suse_osh_registry_location }}/openstackhelm/ironic:{{ suse_osh_image_version }}"
    magnum_api: "{{ suse_osh_registry_location }}/openstackhelm/magnum:{{ suse_osh_image_version }}"
    magnum_conductor: "{{ suse_osh_registry_location }}/openstackhelm/magnum:{{ suse_osh_image_version }}"
    magnum_db_sync: "{{ suse_osh_registry_location }}/openstackhelm/magnum:{{ suse_osh_image_version }}"
    senlin_api: "{{ suse_osh_registry_location }}/openstackhelm/senlin:{{ suse_osh_image_version }}"
    senlin_db_sync: "{{ suse_osh_registry_location }}/openstackhelm/senlin:{{ suse_osh_image_version }}"
    senlin_engine: "{{ suse_osh_registry_location }}/openstackhelm/senlin:{{ suse_osh_image_version }}"
