---
- name: Install helm package
  become: yes
  package:
    name: helm
    state: present
  retries: 5
  delay: 2
  tags:
    - install

- name: Install tiller
  command: helm init --upgrade
  changed_when: True
