---
# tasks file for airship-deploy-tempest
- name: Load standard variables
  include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"
  tags:
    - always

- name: Set site path
  set_fact:
    site_path: "{{ upstream_repos_clone_folder }}/airship/treasuremap/site/{{ socok8s_site_name }}"
  tags:
    - always

- name: Ensure site directory for {{ socok8s_site_name }} exists
  become: yes
  file:
    path: "{{ site_path }}"
    state: directory

- name: Ensure tempest chart directory exists
  become: yes
  file:
    path: "{{ site_path }}/software/charts/osh/openstack-tempest"
    state: directory

- name: Create tempest networking
  include: create_tempest_network.yml

- name: Get m1.tiny flavor ID
  command: "openstack flavor show m1.tiny -f value -c id"
  environment:
    OS_CLOUD: openstack
  register: tempest_test_flavor_id
  changed_when: False

- name: Copy get Cirros image ID script
  copy:
    src: "{{ role_path }}/files/tempest_get_image_id.sh"
    dest: /tmp/tempest_get_image_id.sh
    mode: 0755

- name: Get Cirros image ID
  command: /tmp/tempest_get_image_id.sh
  register: tempest_test_image_id
  changed_when: False

- name: Render tempest.yaml and move to openstack-tempest directory
  become: yes
  template:
    src: "{{ playbook_dir }}/../site/soc/software/charts/osh/openstack-tempest/tempest.yaml"
    dest: "{{ site_path }}/software/charts/osh/openstack-tempest/tempest.yaml"

- name: Move chart-group.yaml to openstack-tempest directory
  become: yes
  copy:
    src: "{{ playbook_dir }}/../site/soc/software/charts/osh/openstack-tempest/chart-group.yaml"
    dest: "{{ site_path }}/software/charts/osh/openstack-tempest/chart-group.yaml"

- name: Reprocess site manifest template for tempest deployment
  become: yes
  template:
    src: "{{ playbook_dir }}/../site/soc/software/manifests/full-site.yaml"
    dest: "{{ site_path }}/software/manifests/full-site.yaml"
  when: deploy_tempest|default(false)|bool

- name: Delete previous tempest test pods if present
  command: "helm delete --purge airship-tempest"
  register: helm_result
  failed_when:
    - helm_result.rc != 0
    - "'not found' not in helm_result.stderr"
  changed_when: helm_result.stdout is search('deleted')

- name: Update site software via Shipyard to configure and execute tempest tests
  block:
    - include_role:
        name: airship-deploy-osh
        apply:
          tags:
            - update_airship_osh_site

  always:
    - name: Get latest tempest run pod name if there
      command: kubectl get pods -n openstack -l application=tempest,component=run-tests --sort-by=.metadata.creationTimestamp --no-headers -o jsonpath="{.items[-1:].metadata.name}"
      ignore_errors: yes
      register: _tempest_run_pod_name

    - name: Log if missing tempest run pod
      debug:
        msg:
          - "Tempest test execution pod not found (likely some software update error)."
          - "Check kubernetes artifact logs for details."
          - "You can gather artifact logs via following command if needed"
          - "./run.sh gather_logs"
      when:
        - _tempest_run_pod_name.rc != 0

    - name: Gather logs from tempest pods if there
      command: "kubectl logs -n openstack {{ _tempest_run_pod_name.stdout }}"
      register: _tempest_logs_out
      when:
        - _tempest_run_pod_name.rc == 0
        - print_tempest_log
        - not tempest_subunit

    - name: Show command for gathering tempest logs
      debug:
        msg:
          - "Tempest job execution is completed. Check the output of this tempest run for details"
          - "kubectl logs -n openstack {{ _tempest_run_pod_name.stdout }}"
      when:
        - _tempest_run_pod_name.rc == 0
        - not print_tempest_log

    - name: Show tempest logs after tempest job execution
      debug:
        msg:
          - "Tempest job execution is completed. Check follwing output for any tempest test failures"
          - "{{ _tempest_logs_out.stdout_lines }}"
      when:
        - _tempest_run_pod_name.rc == 0
        - print_tempest_log
        - not tempest_subunit

    - name: Remove tempest network
      include: remove_tempest_network.yml