---
# defaults file for suse-airship-deploy

# IP on the external network
ext_vip: null

# extra repositories that will be added. key should be the repo name,
# value the repo url
zypper_extra_repos: {}

suse_airship_deploy_packages:
  - ca-certificates
  - curl
  - docker
  - git-core # for download of local-provisioner
  - jq
  - make
  - nmap
  - python3-setuptools
  - python3-pip
  - python3-cmd2
  - python3-devel
  - uuid-runtime

suse_airship_openstackclient_packages:
  - python3-barbicanclient
  - python3-heatclient
  - python3-openstackclient
